### ISSUE TITLE
"x86 MCPE .apk" ?

### ISSUE THREAD

**Issue by Pab450** [mhsjlw/mcpelauncher#2]
I followed your procedure, but I'm still stuck for how to get "x86 MCPE .apk"

**Comment by mhsjlw** [comment]
Well, your options are quite limited. All of them require that you own a copy of Minecraft Pocket Edition for an **Android** device.

1. If you have an x86 phone, just take that off of your device
2. Try using https://github.com/MCMrARM/Google-Play-API (although not certain it will work on macOS, or if it will work at all)
3. If all else fails, you could try to download the `.apk` inside of VirtualBox running Android x86

**Comment by SuperOP535** [comment]
I have an x86 tablet but sharing the APK would be piracy

**Comment by MCMrARM** [comment]
Wait for CEF support :)
